# mappings between abbreviations used by SIS and longer descriptions

# all the mmappings from abbreviations to full-length descriptions
acad_group_mapping = {
    "LEAD": "Batten Leadership & Public Pol",
    "CGAS": "College & Graduate Arts & Sciences",
    "SCPS": "Continuing and Prof Studies",
    "GBUS": "Darden Grad School of Business",
    "ENGR": "Engineering & Applied Science",
    "PROV": "Executive VP & Provost",
    "MCDG": "McIntire Darden Grad Business",
    "COMM": "McIntire School of Commerce",
    "MDS": "Medical School - BIMS/PHS",
    "ARCH": "School of Architecture",
    "DSCI": "School of Data Science",
    "EDUC": "School of Education & HumanDev",
    "LAW": "School of Law",
    "MED": "School of Medicine",
    "NURS": "School of Nursing"
}


traditional_requirement_mapping = {'SW': 'Second Writing Requirement',
 'FL': 'Foreign Language Requirement',
 'HNS': 'Historical Stdy/Non-West/SWR',
 'HS': 'Historical Studies',
 'HSNW': 'Historical Stdy & Non-Western',
 'NW': 'Non-Western Perspectives',
 'SWHS': 'Second Writing & Historical St',
 'SWNW': 'Second Writing & None-Western'}


new_requirement_mapping = {'ASUD-AIP': 'Artistic, Interpretive, Phil',
 'ASUD-CMP': 'Chem/Map/Physical Universe',
 'ASUD-CSW': 'Cultures/Societies World',
 'ASUR-R21C1': 'First Writing',
 'ASUD-HP': 'Historical Perspectives',
 'ASUD-LS': 'Living Systems',
 'ASUD-QCD': 'Quantif, Computation, Data, An',
 'ASUD-SS': 'Science and Society',
 'ASUD-R21C2': 'Second Writing',
 'ASUD-SES': 'Social & Economic Systems',
 'ASUD-WL': 'World Languages'}


acad_org_mapping = {'AAS': 'African-American and African Std',
 'AIRS': 'Air Science',
 'ASL': 'American Sign Language',
 'AMST': 'American Studies',
 'ANTH': 'Anthropology',
 'APMA': 'Applied Mathematics',
 'AM': 'Applied Mechanics',
 'ALAR': 'Arch & Landscape Arch',
 'ARH': 'Architectural History',
 'ARCHDP': 'Architecture Department',
 'ART': 'Art',
 'ASTR': 'Astronomy',
 'BIOC': 'Biochem & Molecular Genetics',
 'BIOL': 'Biology',
 'BIOM': 'Biomedical Engineering',
 'BIMS': 'Biomedical Sciences',
 'BIOP': 'Biophysics',
 'CELL': 'Cell Biology',
 'CHE': 'Chemical Engineering',
 'CHEM': 'Chemistry',
 'CEE': 'Civil and Environmental Engr',
 'CLAS': 'Classics',
 'COGS': 'Cognitive Science',
 'CGAS': 'College & Graduate Arts and Sci',
 'CS': 'Computer Science',
 'EDIS': 'Curriculum Inst & Special Ed',
 'ENGRD': 'Dean Engineering and Applied Sci',
 'ARCHD': 'Dean of Architecture',
 'CGASD': 'Dean of Arts and Sciences',
 'COMMD': 'Dean of Commerce',
 'SCPSD': 'Dean of Continuing & Prof Studs',
 'DATAD': 'Dean of Data Science',
 'EDUCD': 'Dean of Education',
 'GBUSD': 'Dean of Graduate Business',
 'LAWD': 'Dean of Law',
 'MEDD': 'Dean of Medicine',
 'NURSD': 'Dean of Nursing',
 'DRAM': 'Drama',
 'EALC': 'East Asian Lang, Lit & Culture',
 'ECON': 'Economics',
 'ECE': 'Electrical & Computer Engr',
 'STS': 'Engineering & Society',
 'ENGL': 'English',
 'ESL': 'English as a Second Language',
 'EVSC': 'Environmental Sciences',
 'ETP': 'Environmental Thought and Pract',
 'PROVD': 'Executive VP and Provost',
 'FREN': 'French',
 'GERM': 'German',
 'HIST': 'History',
 'EDHS': 'Human Services',
 'IMP': 'Interdisciplinary Major',
 'IDST': 'Interdisciplinary Studies',
 'EDKI': 'Kinesiology',
 'LAR': 'Landscape Architecture',
 'EDLF': 'Leadership, Foundation & Pol',
 'MSE': 'Materials Science & Engr',
 'MATH': 'Mathematics',
 'MCDG': 'McIntire Darden Grad Business',
 'MAE': 'Mechanical & Aerospace Engr',
 'MDST': 'Media Studies',
 'MICR': 'Microbiol, Immun & Cancer Biol',
 'MESA': 'Middle Eastern & South Asian',
 'MISC': 'Military Science',
 'MUSI': 'Music',
 'NASC': 'Naval Science',
 'NESC': 'Neuroscience',
 'PATH': 'Pathology',
 'PHAR': 'Pharmacology',
 'PHIL': 'Philosophy',
 'PHYS': 'Physics',
 'PHY': 'Physiology',
 'PST': 'Political & Social Thought',
 'POLT': 'Politics',
 'PSYC': 'Psychology',
 'PHS': 'Public Health Sciences',
 'PPOL': 'Public Policy',
 'RELG': 'Regiligous Studies',
 'SLLT': 'Slavic',
 'SOC': 'Sociology',
 'SPAN': 'Spanish, Italian & Portugese',
 'STAT': 'Statistics',
 'SIE': 'Systems and Information Engine',
 'PLAN': 'Urban & Environmental Planning',
 'SWAG': 'Women, Gender & Sexuality'}